# Import libraries

In [6]:
import pandas as pd 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

# Import data

In [2]:
iris_2D_mm = pd.read_csv("../data/iris_2D_mm.csv")
iris_2D_mm

Petal_Length  Petal_Width  Label
0           1.4          2.0    0.0
1           1.3          4.0    0.0
2           1.4          3.0    0.0
3           4.0         10.0    1.0
4           4.7         14.0    1.0
5           3.6         13.0    1.0

In [4]:
x_data = iris_2D_mm[["Petal_Length", "Petal_Width"]]
x_data = x_data.to_numpy()
x_data

array([[ 1.4,  2. ],
       [ 1.3,  4. ],
       [ 1.4,  3. ],
       [ 4. , 10. ],
       [ 4.7, 14. ],
       [ 3.6, 13. ]])

In [5]:
y_data = iris_2D_mm[["Label"]]
y_data = y_data.to_numpy()
y_data

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]])

In [15]:
# normalize data
scaler = StandardScaler()
scaler.fit(x_data)

x_data = scaler.transform(x_data)
x_data

array([[-0.94942533, -1.16756479],
       [-1.02063223, -0.7554831 ],
       [-0.94942533, -0.96152395],
       [ 0.90195406,  0.48076197],
       [ 1.40040236,  1.30492536],
       [ 0.61712646,  1.09888451]])

In [9]:
classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_data, y_data)

c:\Users\Nam\anaconda3\envs\Nam\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=6)

### Test case 1

In [14]:
x_test = [[2.6, 0.7]]
# normalize data
x_test = scaler.transform(x_test)
x_test

array([[2.6, 0.7]])

In [11]:
y_pred = classifier.kneighbors(x_test)
y_pred

(array([[1.34349142, 1.71214057, 2.02259643, 3.90223126, 3.91906647,
         4.01076282]]),
 array([[4, 3, 5, 1, 2, 0]], dtype=int64))

### Test case 2

In [12]:
x_test = [[2.6, 7.0]]
# normalize data
x_test = scaler.transform(x_test)
x_test

array([[2.6, 7. ]])

In [13]:
y_pred = classifier.kneighbors(x_test)
print(y_pred)

(array([[5.82004379, 6.2253475 , 6.73675177, 8.55900087, 8.71689645,
        8.9054778 ]]), array([[4, 5, 3, 1, 2, 0]], dtype=int64))
